### ISSUE TITLE
Show model schematic in ReadMe

### ISSUE THREAD

**Issue by ChHaeni** [sashahafner/ALFAM2#12]
Show a model schematic (figure) in the ReadMe file. It would help to get a quick idea of the different parameters (f0,r1,...). 
By the way, why leads 'no incorporation' to f5==1? Or did I misunderstand that?

**Comment by sashahafner** [comment]
>  By the way, why leads 'no incorporation' to f5==1? Or did I misunderstand that?

f5 (f4 in paper) is fraction that stay in F. So it is 1 without incorporation.

**Comment by ChHaeni** [comment]
detail: f4 is equal to f5 in the code... change one of them?

**Comment by ChHaeni** [comment]
oh, just saw your comment... still, shouldn't we change f5 to f4 in the code, so it's clear?

**Comment by sashahafner** [comment]
Yes, I want to change the code. f5 is from an older version of the model that had both f4 (a different f4) and f5. It is an issue, or should be. I think I will tackle it next.

**Comment by sashahafner** [comment]
OK to close now, right?
