### ISSUE TITLE
Vignette not available?

### ISSUE THREAD

**Issue by ChHaeni** [sashahafner/ALFAM2#16]
Vignette seems to be missing in the package:
`vignette(package="ALFAM2")`
results in
`no vignettes found`

**Comment by sashahafner** [comment]
Seems it is a install_github() issue, although there was metadata missing as well. But as of c885097e8ba7a640199da279d7a52bb73d026363 it should work if you install like this:

```
devtools::install_github('sashahafner/ALFAM2', build_vignettes = TRUE)
```

You can then run

```
vignette(package = 'ALFAM2')
```

```
Vignettes in package ‘ALFAM2’:

ALFAM2_quick_start   Getting started with the ALFAM2 package
                     (source, pdf)
```

and use 

```
vignette('ALFAM2_quick_start')
```

and

```
browseVignettes('ALFAM2')
```
Thanks for catching this.

**Comment by ChHaeni** [comment]
Hmm... When I install the package by `R CMD` or `install.pachages()` it doesn't build the vignette as well. Strange that building the vignette is not default...

**Comment by sashahafner** [comment]
That is strange! This is after you download a compressed version from GitHub? Leaving this open for now.

**Comment by ChHaeni** [comment]
No, this is when I install the cloned repo from source with e.g. `install.packages("/path/to/ALFAM2-repo", repos = NULL)`
But don't worry, I'm sure I miss something again. As long as the 'normal' installation ways work that's fine, I guess.

**Comment by ChHaeni** [comment]
I think I will close this issue, since it seems to be related to the fact that R does not build vignettes by default when installing a package from source...
