### ISSUE TITLE
Problems with parallel code and evaluation speed

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/ALFAM2#20]
Something seems to be wrong with the parallel option. First, it is terribly slow. Second, I can't get it to complete. In the example below (with only n = 10) after 100 seconds I get this error:

```
Error in checkForRemoteErrors(val) :
  1000 nodes produced errors; first error: could not find function "calcEmis"
Timing stopped at: 100.8 9.88 141.6
```

Looks like the package is not available in the parallel environments. The parallel option must have worked in the past--I used it for parameter estimation. 

The non-parallel option runs quickly as expected (1.3 seconds for n = 1000).

```
n <- 10

dat0 <- data.frame(ctime = 0:12*6, TAN.app = 48, man.dm = 6, air.temp = 13, wind.2m = 2.7)
datb <- dat0[rep(1:13, n), ]
datb$plot <- factor(rep(1:n, each = 13))

system.time(
  predb <- ALFAM2mod(datb, app.name = 'TAN.app', time.name = 'ctime', TAN.app = 48, 
                     man.dm = 6, air.temp = 13, wind = 2.7, group = 'plot', 
                     warn = FALSE)
)

system.time(
  predb <- ALFAM2mod(datb, app.name = 'TAN.app', time.name = 'ctime', TAN.app = 48, 
                     man.dm = 6, air.temp = 13, wind = 2.7, group = 'plot', 
                     warn = FALSE, parallel = TRUE, n.cpus = 3)
)

```

**Comment by sashahafner** [comment]
Adding incorporation really slows things down. Surprising. With n = 1000, a call with deep incorporation takes 5.7 seconds vs. 1.4 without. With n = 10 000, I got tired of waiting after maybe 10 minutes (vs. ca. 25 s without incorporation).

**Comment by ChHaeni** [comment]
Oh boy, that was some embarrassingly bad parallel implementation I've done.
How should I proceed, fix it in the dev? or master?

**Comment by sashahafner** [comment]
No problem. Let's fix it in dev and then test before merging.

**Comment by ChHaeni** [comment]
Fixed in dev with 9aa247ea1ee9fcf775074b44c50bc14786ba12c7

**Comment by sashahafner** [comment]
Thanks. Seems better than 2x as fast for 10 000 plots and 3 cores. Great! How did the other tests go? 

Is it correct that you used clusterApply() instead of alternatives (mclapply, foreach and dopar) so this works on Windows?

**Comment by ChHaeni** [comment]
Yes, it does work on windows. I ended up using clusterApply with 'PSOCK' since I didn't see any speed improvement with forking as e.g. mclapply does. (I boldly state, that it can't be optimized much from here, since the overhead is now really small. :-)

**Comment by sashahafner** [comment]
As of 7273501e0087a2f822902b89a9abe49f2c8d1bbf (v1.5.0) there is a problem. Might be a simple error in column names. I have not dug into it.

```
> preds <- ALFAM2mod(dat, pars = pars, time.name = 'ct', app.name = 'tan.app', group = 'rid', parallel = TRUE, n.cpus = 3)
User-supplied parameters are being used.
Error in `[.data.frame`(merge(dat, e0, by = "orig.order"), , c("orig.order",  :
  undefined columns selected
```

**Comment by sashahafner** [comment]
Fixed in 42d4c988e3b5e1aebe38b669489b444903da3154. Problem was this merge:

```
 e <- merge(dat, e0, by = "orig.order")[,
```

Both have a ct (time.name) column, so we got auto suffixes x and y. Following column selection didn't work. 

I don't understand why the parallel option seemed to work with simple examples but not this one above (with thousands of group levels). Anyway, no sign of problems at the moment.

**Comment by sashahafner** [comment]
The increase in speed is a big help. Thanks for this parallel option @ChHaeni !

**Comment by ChHaeni** [comment]
How long do your calculations take..? Is it a matter of minutes? hours?
If you would profit from a speed boost, how open would you be to transfer the code from `data.frame`s to `data.table`s? (see https://github.com/Rdatatable/data.table) and/or add C++ Code with `Rcpp` to the core function?

**Comment by sashahafner** [comment]
At the moment I have no need for an improvement in speed. Typically around 500 plots with maybe 13000 rows runs in a few seconds. For parameter estimation, it would be convenient to have it run faster, but this is not a priority right now. I think compiled code would be a good approach, but I expect that would take a lot of effort. Good suggestion with data.tables. I've read good things.

**Comment by ChHaeni** [comment]
I absolutely love the `data.table` package and almost exclusively use it over standard `data.frame`s!
I think, once you realise the possible pitfall of forgetting to actively _deep copy_ in some circumstances and you get used to the change in syntax, you will never want to use `data.frame` syntax anymore - it just feels so clumsy :)

**Comment by sashahafner** [comment]
Problem with parallel option, dat does not have the model output columns here around line 324 so this merge fails:

```
    e <- merge(dat, e0, by = c("orig.order", time.name))[,
      c("orig.order", group, names(e0)[-1], pass.col)]
```

**Comment by sashahafner** [comment]
Probably a problem that resulted from the dummy variable addition (`prep` argument). I need to turn off parallel for now, and finish improving code efficiency before we attach this parallel issue again (if we still need it).

**Comment by sashahafner** [comment]
No parallel option anymore.
Closing.
