### ISSUE TITLE
Strange output with variable name error (cmns)

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/ALFAM2#21]
Why does this (pH instead of ph) give nearly 100% emission?

**Comment by sashahafner** [comment]
```
pred6.0.S <- ALFAM2mod(dat6.0, group = 'app.mthd', TAN.app = 100, warn = FALSE,
                       cmns = c(man.pH = 7.0))
```

**Comment by sashahafner** [comment]
Here is a reproducible example. With the `cmns` argument, `f0` and `r1` change, and `er > 90%`.
```
library(ALFAM2)

dat <- data.frame(ct = 72, TAN.app = 50, man.dm = 8, air.temp = 20, wind.2m = 3, app.mthd.bc = TRUE)

args(ALFAM2mod)

ALFAM2mod(dat, TAN.app = 100, cmns = c(man.pH = 7.5), warn = FALSE)
ALFAM2mod(dat, TAN.app = 100, warn = FALSE)
```

**Comment by ChHaeni** [comment]
The change in `er` is due to missing centering of the provided coumns. Only columns are centered where we provide a value in argument `cmns`. So you'd need to provide `cmns = c(app.rate = 40, man.dm = 6, air.temp = 13, wind.2m = 2.7)` as argument.
In my opinion, this behavior should be changed. I think it is more intuitive to have the columns centered by default and if you really want them uncentered, you'd need to supply `cmns = c(man.dm = 0)` for example.
But I leave this up to @sashahafner.

If we decide to change the behavior, a possible way could be:
```r
# get defaults              
cmns_defaults <- eval(formals(ALFAM2::ALFAM2mod)$cmns)

# add/replace provided column means                                                                                                       
cmns <- c(cmns, cmns_defaults[!(names(cmns_defaults) %in% names(cmns))])
```

**Comment by sashahafner** [comment]
Ah, of course. The call that resulted in unexpected behavior was just plain wrong. 

I agree that `cmns` should act like the `add.pars` argument we discussed in #22, i.e., only revise or extend the default values. Your solution looks good to me! Can you add it to dev?

**Comment by ChHaeni** [comment]
I wonder if we should add the default `cmns` values as data, just as you did with the `pars`. 
I guess, these values are also closely related to any new `pars` estimates from an (in the future) possibly extended database? So one could choose `ALFAM2cmns02` with `ALFAM2pars02` and  `ALFAM2cmns03` with `ALFAM2pars03`...?

Some further points I think we should consider:
- all model users except @sashahafner will (or say: should) use default values for both `pars` and `cmns`
- linking `pars` to different `cmns` - does that really make sense?

So - should we really provide such an 'easy flexibility' with the model function? Or could we remove arguments `pars` and `cmns` and add a new argument `calibration='version1'` (well, with a better argument name - but you get the idea...) where the correct `pars` and `cmns` are derived accordingly? And then we could move `pars = NULL, cmns = NULL` to the end of the function arguments to still provide the needed flexibility?

**Comment by sashahafner** [comment]
Very good points. The `cmns` argument is a "dangerous" one, and should probably be linked with parameter values as you proposed. So far it has never changed but might in the future. 

I like the idea of a single argument with both, but am concerned about backward compatibility. (I know we may still be the only people who uses the package, but it is already used in a few cases for emission factor calculations.) For now, maybe we should add a warning for any time the cmns argument is given by a user.

**Comment by sashahafner** [comment]
Added a warning. Good enough for now I think.
c49c0371f8d99de7cae9d97e0200173ecc0478ec

**Comment by sashahafner** [comment]
See #64

**Comment by sashahafner** [comment]
Now with extend/replace behavior as @ChHaeni suggested above.
Works as expected (center is 2.7 by default for wind):

```
> packageVersion('ALFAM2')
[1] ‘3.96’
> dat1 <- data.frame(ctime = 168, TAN.app = 50, man.dm = 8, air.temp = 20, wind.
2m = 3, app.mthd = 'bc')
> alfam2(dat1, app.name = 'TAN.app', time.name = 'ctime', warn = FALSE)$er
[1] 0.6809881
> alfam2(dat1, app.name = 'TAN.app', time.name = 'ctime', center = c('abc' = 2),
 warn = FALSE)$er
[1] 0.6809881
> alfam2(dat1, app.name = 'TAN.app', time.name = 'ctime', center = c('wind.2m' =
 10), warn = FALSE)$er
[1] 0.6359945
> alfam2(dat1, app.name = 'TAN.app', time.name = 'ctime', center = c('wind.2m' =
 2.7), warn = FALSE)$er
[1] 0.6809881
```

**Comment by sashahafner** [comment]
988525e6057e30336cfb4a9af61726ffb0163418
