### ISSUE TITLE
add_pars argument

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/ALFAM2#22]
It would be convenient to have an argument that allows one or a few parameters to be added or changed without specifying the complete parameter list again. This is analogous to the add_pars argument in the mamemo project.

**Comment by sashahafner** [comment]
As in the ABM package

**Comment by ChHaeni** [comment]
If I understand correctly, you think about something similar to the following?
```r
if (missing(pars)) {
  ...
} else {
  pars <- c(pars, ALFAM2::ALFAM2pars02[!(names(ALFAM2::ALFAM2pars02) %in% names(pars))])
}
```
Is that correct?

**Comment by sashahafner** [comment]
Yup, I think that would both update/change `ALFAM2pars02` and extend it. Nice! But it should be a different argument, maybe `add.pars`, so that `pars` can still be used to completely override default values.

```
if (!missing(add.pars)) {
  pars <- c(add.pars, ALFAM2::ALFAM2pars02[!(names(ALFAM2::ALFAM2pars02) %in% names(add.pars))])
}
```

And we have to think about the fancy flexibility in how `pars` can be specified.

**Comment by sashahafner** [comment]
I've finally added `add.pars` to do this.

840ad420e9e19304a12cb021f89cff00bfe65472
