### ISSUE TITLE
Emission reduction at high DM

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/ALFAM2#26]
For default predictor variable values, 72 h emission drops above around 9.5%. This must be due to the reduction in r1. Is it realistic?

```
dat <- data.frame(man.dm = 1:100/10, TAN.app = 100, ct = 72)
dat$id <- 1:nrow(dat)
pred <- ALFAM2mod(dat, app.name = 'TAN.app', time.name = 'ct', group = 'id')

plot(er ~ man.dm, data = dat, type = 'l', xlab = 'Time (h)',
ylab = '72 h cum. emission (frac. applied TAN)')
```

**Comment by ChHaeni** [comment]
There's even a more pronounced difference for cumulative emissions after less time, e.g. 4h:
```r
dat <- data.frame(man.dm = 1:100/10, TAN.app = 100, ct = 4)
dat$id <- 1:nrow(dat)
pred <- ALFAM2mod(dat, app.name = 'TAN.app', time.name = 'ct', group = 'id')

plot(er ~ man.dm, data = cbind(pred, dat), type = 'l', xlab = 'Manure DM (%)',
    ylab = '72 h cum. emission (frac. applied TAN)')
```
![image](https://user-images.githubusercontent.com/17614871/141482008-8a168ad8-04fe-4a8a-a50c-bd3eb228265e.png)

**Comment by sashahafner** [comment]
> There's even a more pronounced difference for cumulative emissions after less time, e.g. 4h:

That general difference is not implausible. At early times, it is the volatilization rate that tends to limit loss, while over longer periods, it is the total quantity of TAN available that limits how much is lost. 

But this observations is helpful--it gives me an idea for how to test for this model prediction. We could try to compare emission vs. DM for early and late periods. This might be a way to cut through all the noise.

**Comment by sashahafner** [comment]
Here is measured (filled) and calculated (open) 7 d (or close) cumulative emission for all available micromet measurements.

![image](https://user-images.githubusercontent.com/35272876/141638188-eb31abfa-da8e-4f1d-8888-a04dc97e3ff0.png)

**Comment by sashahafner** [comment]
Another crude evaluation of the model's DM effect here:

![image](https://user-images.githubusercontent.com/35272876/145197274-b8b24096-6950-41bc-abfc-dadd94c3d687.png)

Data compiled from the literature on slurry separation (thanks JMP at AU) and plot is from https://github.com/sashahafner/AU-myndighedsbetjening. Arrows show cumulative NH3 emission without separation (tail) or with separation (head). Most measurements (all for broadcast) were with chambers, wind tunnels, or even in the lab, so I am not worried about poor comparison. And weather inputs are missing for most (defaults used). Separation decreases DM and slightly increases pH in general.
