### ISSUE TITLE
Keep original levels

### ISSUE THREAD

**Issue by ChHaeni** [sashahafner/ALFAM2#36]
What is the idea behind providing the option to keep the original columns with possibly altered categories?
Is it an option for the user to better manipulate the data based on its categories? If so, I would suggest to keep the original categories..?

EDIT: I mean e.g. the following:
```r
dat <- data.frame(ct = 168, app.mthd = c('open slot injection', 'cs', 'bsth'))
prepDat(dat, value = 'x')
```
results in
```r
   ct app.mthd app.mthd.os app.mthd.cs
1 168       os           1           0
2 168       cs           0           1
3 168     bsth           0           0
```
whereas I think it should be
```r
   ct            app.mthd app.mthd.os app.mthd.cs
1 168 open slot injection           1           0
2 168                  cs           0           1
3 168                bsth           0           0
```

_Originally posted by @ChHaeni in https://github.com/sashahafner/ALFAM2/pull/34#issuecomment-966576666_

**Comment by sashahafner** [comment]
I guess it was initially for checking that the dummy variables were correctly created. I'm open to changing the default behavior and options. 

A few thoughts:
* `prepDat()` is not going to be an exported function, so users will not work with it directly (typically)
* It is indeed a bit confusing to have the function return the altered categories under the original column names (I think your question is a good one)
* `ALFAM2mod()` only needs dummy output (see below)

Based on all this, why don't we just remove the `value` argument and return only the dummy variables? The only drawback is that checking the conversion is slightly harder, but a `cbind()` call can be used (whether working with `prepDat()` directly or `ALFAMwmod()`. We could use `attributes` to list the original variables that have been converted to dummies, for the user to check. The message on parameter values used/not used also provides some info on this.

What do you think?

**Comment by ChHaeni** [comment]
Yes, I think you're right, we can remove the `value`.
I'll close this issue and the corresponding PR #34.
