### ISSUE TITLE
Likely errors in database

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/ALFAM2#8]
pmid 1517 1537 and 1538 have very high ct (cumulative time) values.

**Comment by sashahafner** [comment]
At least for 1517 (file "7 ALFAM2_LI94_INCORP v5.xlsx" first row 396) the problem seems to be an error in manure application time

**Comment by ChHaeni** [comment]
Should this be transfered to [sashahafner/ALFAM2-data](https://github.com/sashahafner/ALFAM2-data)?

**Comment by sashahafner** [comment]
Yes.
