### ISSUE TITLE
r3 no longer changes at time of incorporation

### ISSUE THREAD

**Issue by sashahafner** [sashahafner/ALFAM2#9]
r3 needs to be able to change at the time of incorporation. Currently it seems looks fixed for the entire simulation. May have been a change made in commit 00dfe508b431a3715ce098035c2cc5efbdb88815

**Comment by sashahafner** [comment]
Here is some older code (before GitHub) that worked (I think). This was in the afMod(), which is now ALFAM2Mod(). See bold bit at bottom. Also complete file is attached.
[afMod.txt](https://github.com/sashahafner/ALFAM2/files/2405459/afMod.txt)

    for(i in sort(unique(dat[, group]))) {
      dd <- dat[dat[, group] == i, ]
      tt <- dd[1, time.incorp]

      if(!is.na(tt)) { 

        # If exact time is already present, no need to add row
        if(!tt %in% dd[, time.name]) {
          irow <- dd[1, ]
          irow$added.row <- TRUE
          irow[, time.name] <- tt
          dat <- rbind(dat, irow)
        } 

        # Identify time of incorporation event
        dat[dat[, group] == i & dat[, time.name] == tt, 'ievent'] <- TRUE

        **# Set incorporation predictor variables to FALSE for times before incorporation occurred
        dat[dat[, group] == i & dat[, time.name] <= tt, grep('incorp', names(dat))] <- FALSE**

      }

    }

**Comment by sashahafner** [comment]
How about adding an argument incorp.names = c("^incorp", "anything else?") and then use grep/grepl with ignore.case = TRUE to find matches. Values would all be set FALSE/0 for ct < time.incorp. Users could set incorp.names to the exact names of incorporation columns to be careful.

**Comment by ChHaeni** [comment]
Since incorporation takes place at the end of interval *i* by f5, should r3 change from *i+1* onwards?

**Comment by ChHaeni** [comment]
> 
> 
> Here is some older code (before GitHub) that worked (I think). This was in the afMod(), which is now ALFAM2Mod(). See bit at bottom "# Set incorp...". Also complete file is attached.
> [afMod.txt](https://github.com/sashahafner/ALFAM2/files/2405459/afMod.txt)
> 
> ```
> for(i in sort(unique(dat[, group]))) {
>   dd <- dat[dat[, group] == i, ]
>   tt <- dd[1, time.incorp]
> 
>   if(!is.na(tt)) { 
> 
>     # If exact time is already present, no need to add row
>     if(!tt %in% dd[, time.name]) {
>       irow <- dd[1, ]
>       irow$added.row <- TRUE
>       irow[, time.name] <- tt
>       dat <- rbind(dat, irow)
>     } 
> 
>     # Identify time of incorporation event
>     dat[dat[, group] == i & dat[, time.name] == tt, 'ievent'] <- TRUE
> 
>     # Set incorporation predictor variables to FALSE for times before incorporation occurred
>     dat[dat[, group] == i & dat[, time.name] <= tt, grep('incorp', names(dat))] <- FALSE
> 
>   }
> 
> }
> ```

Can you please help me, I'm struggling to see where r3 changes at time of incorporation in your code...

**Comment by ChHaeni** [comment]
First part of issue should be solved now with commit [`a80691a`](https://github.com/sashahafner/ALFAM2/commit/a80691ae60de198f5c19d020c9988d3d5b4bbae2).

**Comment by sashahafner** [comment]
It was this line that changed it, if there was some incorp3 secondary parm:

    dat[dat[, group] == i & dat[, time.name] <= tt, grep('incorp', names(dat))] <- FALSE

Have not looked at commit yet. But thanks :)

**Comment by sashahafner** [comment]
> Since incorporation takes place at the end of interval _i_ by f5, should r3 change from _i+1_ onwards?

Yes! So incorp variables should be set to 0/FALSE if time <= incorp time.

**Comment by sashahafner** [comment]
Presently (commit 2d2f65d28b9a6bb85a4d84a78d57d3a05e8f1649 and probably long before), if e.g., incorp.deep = TRUE but t.incorp = NA, r3 still changes. In this case there is no incorporation time given, we should assume there is no incorporation, and r3 should not change. Working on this now.

**Comment by sashahafner** [comment]
Fixed this latest t.incorp = NA issue with commit 50a3186be009018181beb01380f315a482a4c257
